spring.datasource.url=${DB_URL:jdbc:oracle:thin:@//localhost:1521/FAMILHASPDB}
spring.datasource.username=${DB_USERNAME:familhas}
spring.datasource.password=${DB_PASSWORD:familhas123}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.sql.init.mode=never
spring.flyway.enabled=true
